version: '3.3'

services:

  entrypoint-service-database:
    image: 'postgres'
    container_name: entrypoint-service-database
    environment:
      - POSTGRES_USER=entrypoint-service-user
      - POSTGRES_PASSWORD=entrypoint-service-password
      - POSTGRES_DB=entrypoint-service-database
    volumes:
      - entrypoint-service-database-data:/var/lib/postgresql/data
    ports:
      - "49003:5432"

volumes:
  entrypoint-service-database-data:
