version: '3.3'

services:

  customer-service-database:
    image: 'postgres'
    container_name: customer-service-database
    environment:
      - POSTGRES_USER=customer-service-user
      - POSTGRES_PASSWORD=customer-service-password
      - POSTGRES_DB=customer-service-database
    volumes:
      - customer-service-database-data:/var/lib/postgresql/data
    ports:
      - "49004:5432"

volumes:
  customer-service-database-data:
