version: '3.3'

services:

  dictionary-service-database:
    image: 'postgres'
    container_name: dictionary-service-database
    environment:
      - POSTGRES_USER=dictionary-service-user
      - POSTGRES_PASSWORD=dictionary-service-password
      - POSTGRES_DB=dictionary-service-database
    volumes:
      - dictionary-service-database-data:/var/lib/postgresql/data
    ports:
      - "49007:5432"

volumes:
  dictionary-service-database-data:
