version: '3.3'

services:

  disctionary-service-database:
    image: 'postgres'
    container_name: disctionary-service-database
    environment:
      - POSTGRES_USER=disctionary-service-user
      - POSTGRES_PASSWORD=disctionary-service-password
      - POSTGRES_DB=disctionary-service-database
    volumes:
      - disctionary-service-database-data:/var/lib/postgresql/data
    ports:
      - "49007:5432"

volumes:
  disctionary-service-database-data:
